export const QuestionActionTypes = {
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  CHOSEN_ANSWER: "CHOSEN_ANSWER",
  SET_SCORE: "SET_SCORE",
  START_EXAM: "START_EXAM",
  INPUT_CHANGE: "INPUT_CHANGE",
  RESET_EXAM: "RESET_EXAM",
};
